---
framework: jest
preRun:
     command:
        - npm ci
        - npm run build
preMerge:
  pattern:
    - "./src/**/__tests__/*.jest.js"
postMerge:
  pattern: 
    - "./src/**/__tests__/*.jest.js"
postRun:
     command:
        - node --version
version: 1.0
